### PR TITLE
Remove ZSOCK_MSG_TRUNC for offloaded TLS on nRF9160.

### LINKED ISSUE #417: Will not receive data using offloaded socket/TLS on nRF9160
### Zephyr Commit hash

28a3fca7da5cfb3b72f1a874b3b7fa62f713ab3d

### Golioth SDK Commit Hash

bbae6f8419ed52acd74784ed7e876a0f24e75f8b

### Hardware Target

circuitdojo_feather_nrf9160_ns

### What host OS are you using?

```
❯ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

### Current Behavior

I'm trying to use the offloaded socket/TLS through the modem firmware on the nRF9160. I get a successful connection but when the client goes to receive data the connection fails:

```
[00:00:07.388,732] <inf> modem: Disconnected
[00:00:07.388,763] <inf> modem: LTE cell changed: Cell ID: 13379857, Tracking area: 1544
[00:00:10.768,463] <inf> modem: Network registration status: Connected - roaming
[00:00:10.768,768] <inf> golioth_system: Starting connect
[00:00:10.769,714] <inf> modem: Sleep PSM
[00:00:15.767,028] <inf> app: Connected to Golioth!
[00:00:15.767,089] <inf> app: Sending hello! 0
[00:00:15.767,700] <inf> golioth_system: Client connected!
[00:00:16.067,169] <err> golioth_system: Failed to receive: -95
```

The error message -95 corresponds to the error code EOPNOTSUPP, which stands for "Operation not supported". 

While looking into the depths of the API documentation, it looks like ZSOCK_MSG_TRUNC is not supported by [nrfxlib](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.4.1/nrfxlib/nrf_modem/doc/api.html#socket-send-and-recv-flags) 

### Expected Behavior

The Golioth client connect and receive data without issue when using offloaded sockets/TLS.

### Steps To Reproduce

Set 

```
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
```

In config. Do not modify `CONFIG_NET_SOCKETS_TLS_PRIORITY` since we want the offloaded sockets.

Set the supported cipher suite:

```
CONFIG_GOLIOTH_CIPHERSUITES="TLS_PSK_WITH_AES_128_CBC_SHA256"
```

Load PSK to the device using `AT%CMNG` AT command.

Then try connecting.

### Logs, console output, or any kind of debug information

```shell
Removing the usage of `ZSOCK_MSG_TRUNC` allows the offloaded socket/(D)TLS connection to work.
```

### PR DESCRIPTION
**Pull request by jaredwolff**
Creating an extra #ifdef conditional for handling recv flags when the connection socket is offloaded. ZSOCK_MSG_TRUNC is not supported on the nRF9160 modem firmware/library.

Fixes #417 

Signed-off-by: Jared Wolff (Circuit Dojo LLC)

### CODE REVIEW

File: net/golioth/golioth.c [hunk 1]
```diff
@@ -532,8 +532,16 @@ int golioth_process_rx(struct golioth_client *client)
 	int ret;
 	int err;
 
+	/* nRF9160 does not support ZSOCK_MSG_TRUNC */
+#if CONFIG_NET_SOCKETS_OFFLOAD && CONFIG_NET_SOCKETS && CONFIG_NRF_MODEM_LIB
+	int flags = ZSOCK_MSG_DONTWAIT;
+#else 
+	int flags = ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_TRUNC;
+#endif
+
```
Comment (mniestroj) [inline net/golioth/golioth.c:541]: I'd prefer to introduce new Kconfig option like:
```
config GOLIOTH_RECV_USE_MSG_TRUNC
        bool "Use MSG_TRUNC in recv()"
        default y if NET_NATIVE && !NET_SOCKES_OFFLOAD
        help
          Use MSG_TRUNC flag in recv() API calls. This allows to receive truncated
          packets and renegotiate smaller blocks in CoAP packets in case configured
          receive buffer is too small.
```

Then we can use `IS_ENABLED(CONFIG_GOLIOTH_RECV_USE_MSG_TRUNC)` to construct `flags` without too much ifdef'fery in C code.

**Review by mniestroj — CHANGES_REQUESTED** [review]
Thanks for contribution!

Please see my comment about new Kconfig option. Could you also fix gitlint/checkpatch CI failures?

**Comment by jaredwolff** [comment]
@mniestroj good call. I've made the changes. Let me know if that works.

File: net/golioth/golioth.c [hunk 2]
```diff
@@ -532,8 +532,16 @@ int golioth_process_rx(struct golioth_client *client)
 	int ret;
 	int err;
 
+	/* nRF9160 does not support ZSOCK_MSG_TRUNC */
+#if IS_ENABLED(CONFIG_GOLIOTH_RECV_USE_MSG_TRUNC)
+	int flags = ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_TRUNC;
+#else 
+	int flags = ZSOCK_MSG_DONTWAIT;
+#endif
```
Comment (mniestroj) [inline net/golioth/golioth.c:540]:
```suggestion
	int flags = ZSOCK_MSG_DONTWAIT |
		(IS_ENABLED(CONFIG_GOLIOTH_RECV_USE_MSG_TRUNC) ? ZSOCK_MSG_TRUNC : 0);
	int ret;
	int err;
```

File: net/golioth/golioth.c [hunk 3]
```diff
@@ -532,8 +532,16 @@ int golioth_process_rx(struct golioth_client *client)
...
+
 	ret = golioth_recv(client, client->rx_buffer, client->rx_buffer_len,
-			   ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_TRUNC);
+			   flags );
```
Comment (mniestroj) [inline net/golioth/golioth.c:543]:
```suggestion
			   flags);
```

File: net/golioth/golioth.c [hunk 4]
```diff
@@ -532,8 +532,16 @@ int golioth_process_rx(struct golioth_client *client)
...
+
```
Comment (mniestroj) [inline net/golioth/golioth.c:544]: This newline is unnecessary.

**Comment by jaredwolff** [comment]
@sam-golioth fixed that last Git lint

**Comment by sam-golioth** [comment]
> @sam-golioth fixed that last Git lint

Thanks @jaredwolff! I'll merge once CI completes.
